name: chocolatine

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env: 
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-NAN-2-1-chocolatine-simon.ganier-lombard.git"
  EXECUTABLES: "test"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - id: check_coding_style
        run: check.sh $(pwd) $(pwd)
      - name: Anotation of the coding style
        run: |
          cat coding-style-reports.log | while read line; do
            echo "::error file=$(echo $line | cut -d ':' -f 1),\
          line=$(echo $line | cut -d ':' -f 2),title=$(echo $line | cut -d ':' -f 3)"\
           coding style error"::$(echo $line | cut -d ':' -f 4)"
          done
          if [ -s coding-style-reports.log ]; then
            exit 1
          else
            echo "::notice::No coding style error found."
          fi
        
  
